### ISSUE TITLE
Hideki Protocol

### ISSUE THREAD

**Issue by noxx2015** [pimatic/pimatic-homeduino#55] opened 2016-01-28 13:59 UTC
Please add the support for Weatherstations with Hideki Protcoll, like TFA Nexus.

- rain [mm]
- - correction factor for rain [ ]
- rain rate [mm/h]
- temperature [°C]
- humidity [%]
- wind speed [km/h]
- wind direction [ 0-359°]
- wind speed, gust [km/h]
- wind direction, gust [0-359°]
- battery status [High / Low]
- dewpoint [°C]

Regard

**Comment by Icesory** [comment] 2016-01-28 21:48
duplicate of
https://github.com/pimatic/rfcontroljs/issues/68

It is an serial protocol and cant be decode by the actual homeduino software. This will definitely not done until mid summer.

**Comment by noxx2015** [comment] 2016-01-29 10:52
summer 2016 sounds good.
thx for this

**Comment by mwittig** [comment] 2016-01-29 14:18
@Icesory I think, this ticket should be closed in favour of pimatic/rfcontroljs#68 

It is better to have one ticket to report, discuss, and track progress. Thanks

**Comment by Icesory** [comment] 2016-01-29 17:21
@mwittig is right.

**Closed by Icesory** 2016-01-29 17:21 UTC
